import "./globals.css";



/* Project step by step
* pages user registration
* MongoDB connection
* save user record in DB (server actions)
* Next-auth config
* user login
* admin page
* product collections
* individual project
* calendar component
* user booking records (cart)
* deployment
* */
export const metadata = {
  title: "Resort Booking Next APP",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
    >
      <body >
        {children}
      </body>
    </html>
  );
}
